[package]
name = "bevy_flair"
version = "0.1.0"
edition = "2021"
description = "Bevy UI styling using CSS"
license = "MIT OR Apache-2.0"
categories = ["games", "game-development"]
keywords = ["style", "animations", "bevy", "css"]
repository = "https://github.com/eckz/bevy_flair"
rust-version = "1.80.0"

[lib]
bench = false

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.16.0-dev", git = "https://github.com/bevyengine/bevy.git", default-features = false, features = [
    "std",
    "bevy_ui"
] }
bevy_flair_core = { path = "crates/bevy_flair_core", version = "0.1.0" }
bevy_flair_style = { path = "crates/bevy_flair_style", version = "0.1.0" }
bevy_flair_css_parser = { path = "crates/bevy_flair_css_parser", version = "0.1.0" }

[dependencies]
bevy = { workspace = true }
bevy_flair_core = { workspace = true }
bevy_flair_style = { workspace = true }
bevy_flair_css_parser = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
bevy = { workspace = true, features = [
    "bevy_ui",
    "bevy_text",
    "bevy_picking",
    "bevy_ui_picking_backend",
    "bevy_winit",
    "bevy_gilrs",
    "png",
    "bevy_dev_tools",
    "default_font",
    "x11"
] }

[features]
default = []

[[bench]]
name = "flair_benches"
harness = false

[profile.dev.package."*"]
opt-level = 1
